### ISSUE TITLE
cdn.polyfill.io/v1 not accessible from west europe/germany

### ISSUE THREAD

**Issue by msbannert** [Financial-Times/polyfill-service#2743]
since Feb-27-2023, a https request to https://cdn.polyfill.io/v1/polyfill.min.js returns 404 on many locations of the world (but not all), so there seems to be an issue with the CDN.

it is succeeding for US
it is failing in Germany

Please see this [issue](https://github.com/Financial-Times/polyfill-service/issues/2739), but your fix lasted only some days until it came back.

Thanks
Martin

**Comment by JakeChampion** [comment]
This would be very surprising, because cdn.polyfill.io/v1/polyfill.min.js is handled entirely within the cdn itself and should always return a HTTP/2.0 301 Moved Permanently with the location header set to `/v2/polyfill.min.js`

I've tried making requests from Germany and they seem to all work for me unfortunately. Do you have any more information that could help me debug this situation?

**Comment by msbannert** [comment]
Hmm, you're right, it does work now even from germany.
Our ping test shows that the situation recovered on 27-Apr 16:00 UTC.

So i guess it does not make that much sense to spend more time on that issue.

Thanks
Martin
